# **Assignment For Numpy**

**Name** : Abdullah Zahid 

**Roll No.**: PIAIC142504

**Batch**: 34

**Session**: 4

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [3]:
vector1 = np.arange(10, 50)

4. Find the shape of previous array in question 3

In [4]:
print("The shape of array is: ", vector1.shape)

The shape of array is:  (40,)


In [5]:
print("The shape of array is: ", np.shape(vector1))

The shape of array is:  (40,)


5. Print the type of the previous array in question 3

In [6]:
print("The type of vector:", type(vector1))

The type of vector: <class 'numpy.ndarray'>


In [7]:
print("The data type of array: ", vector1.dtype)

The data type of array:  int32


6. Print the numpy version and the configuration


In [8]:
print("The version of Numpy is: ", np.__version__)

The version of Numpy is:  1.18.1


Or

In [9]:
print("The version of Numpy is: ", np.version.version)

The version of Numpy is:  1.18.1


In [10]:
print("The Configuration of Numpy is: ", np.show_config())

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 

7. Print the dimension of the array in question 3


In [11]:
vector1.ndim

1

Or

In [12]:
np.ndim(vector1)

1

8. Create a boolean array with all the True values

In [13]:
BooleanVector = np.ones(10,dtype = bool)
BooleanVector

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [14]:
Vector_2D_Ones = np.ones((2,5))
Vector_2D_Ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.arange(8).reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [16]:
np.array([[1,2,3,4,5],[6,7,8,9,10]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

10. Create a three dimensional array



In [17]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [18]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [19]:
Vector2 = np.arange(5)
print("The array is: ", Vector2)
Reversed_Vector = Vector2[::-1]
print("The reversed vector is: ", Reversed_Vector)

The array is:  [0 1 2 3 4]
The reversed vector is:  [4 3 2 1 0]


12. Create a null vector of size 10 but the fifth value which is 1 

In [20]:
Vector3 = np.zeros(10)
Vector3[4] = 1
Vector3

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [21]:
identity_mat = np.identity(3)
identity_mat


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [22]:
arr = np.array([1, 2, 3, 4, 5])
print("The type of arr is: ", arr.dtype)
arr = arr.astype("float16")
print("new type of arr is:", arr.dtype)

The type of arr is:  int32
new type of arr is: float16


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [23]:
arr1 = np.array([[1., 2., 3.],
                 [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],
                 [7., 2., 12.]])

pro_arr = arr1 * arr2

print("Multiplication of both vectors are: \n", pro_arr)

Multiplication of both vectors are: 
 [[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [24]:
arr1 = np.array([[1., 2., 3.],
                 [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],
                 [7., 2., 12.]])

In [25]:
arr_gt = arr1 > arr2
arr_gt

array([[ True, False,  True],
       [False,  True, False]])

In [26]:
arr_lt = arr1 < arr2
arr_lt

array([[False,  True, False],
       [ True, False,  True]])

In [27]:
arr_eq = arr1 == arr2
arr_eq

array([[False, False, False],
       [False, False, False]])

In [28]:
arr_neq = arr1 != arr2
arr_neq

array([[ True,  True,  True],
       [ True,  True,  True]])

17. Extract all odd numbers from arr with values(0-9)

In [29]:
arr4 = np.arange(10)
odds = arr4[arr4 % 2 == 1]
odds

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [30]:
arr4[arr4 % 2 == 1] =-1
arr4

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [31]:
arr = np.arange(10)
indices = [5,6,7,8]

arr[indices] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [32]:
arr = np.ones((4, 5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
arr[1:-1,1:-1]=0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [34]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6], 
                  [7, 8, 9]])

arr2d[1,1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [35]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0][0] = 64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [36]:
arr = np.arange(10).reshape(2,5)
sliced_arr = arr[0]
sliced_arr

array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [37]:
arr = np.arange(10).reshape(2,5)
sliced_arr = arr[1]
sliced_arr

array([5, 6, 7, 8, 9])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [38]:
arr = np.arange(10).reshape(2,5)
sliced_arr = arr[0:2,3]
sliced_arr

array([3, 8])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [39]:
arr = np.random.randint(1, 50, size = (10, 10))
arr

array([[37, 43, 17, 36, 16, 25, 48, 13, 30, 44],
       [ 1, 26, 31, 42, 27, 27, 47, 38, 34, 47],
       [23, 16, 49, 31, 25, 19, 25, 13, 23, 34],
       [16, 37, 45, 47, 26, 30, 42, 30, 47, 19],
       [ 4, 31, 47, 15, 10, 23, 35,  9, 11, 40],
       [35, 44,  5, 20, 16, 38,  6, 23, 33,  5],
       [13, 32, 26, 14, 24, 16, 47, 28, 44, 15],
       [ 5, 43, 28, 35, 24, 42, 19,  7, 21,  9],
       [38, 45, 36, 33, 29, 14, 16,  9, 15, 10],
       [28, 41, 14, 12, 40, 10, 46,  2, 13,  3]])

In [40]:
print("The Max Value in array is: ", arr.max())

The Max Value in array is:  49


or

In [41]:
print("The Max Value in array is: ", np.max(arr))

The Max Value in array is:  49


In [42]:
print("The Min Value in array is: ", arr.min())

The Min Value in array is:  1


In [43]:
print("The Min Value in array is: ", np.min(arr))

The Min Value in array is:  1


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [44]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])

comm_arr = np.intersect1d(a,b)
comm_arr

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [45]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [46]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print("Data is :\n", data)

ext_data = data[names!="Will"]

print("Data where name is not Will\n", ext_data)

Data is :
 [[ 1.92381517  0.5238763  -1.27317517  1.29772286]
 [-0.62963409  0.06562738  0.8180194   0.34590085]
 [-1.18994734 -0.52569588 -0.63915466  0.95585335]
 [-0.4577944  -1.76321696  1.22579348  0.04709309]
 [-0.11320167 -0.74294472 -0.80351014 -0.62795836]
 [ 0.17625989 -1.49112917 -0.92872174  1.4394751 ]
 [-0.46782136 -0.42503412 -0.78688197 -0.01841521]]
Data where name is not Will
 [[ 1.92381517  0.5238763  -1.27317517  1.29772286]
 [-0.62963409  0.06562738  0.8180194   0.34590085]
 [-0.4577944  -1.76321696  1.22579348  0.04709309]
 [ 0.17625989 -1.49112917 -0.92872174  1.4394751 ]
 [-0.46782136 -0.42503412 -0.78688197 -0.01841521]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [47]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)

print("Data is :\n", data)

ext_data = data[np.logical_and(names != "Will", names != "Joe")]


print("Data where name is not Will\n", ext_data)

Data is :
 [[-0.537603    1.10484444  0.29149509 -0.70567684]
 [ 1.07119903  0.87673969  0.7402172   0.45520644]
 [-0.02788638  0.73101215  1.69712287 -1.10980662]
 [-0.02148982 -0.84863503 -0.06717231 -1.12243995]
 [ 0.50647493  1.63808398  0.44027908  0.87603868]
 [ 0.29718778  1.7451161   2.50774756 -0.05604548]
 [ 1.11097132  0.30440549  0.2442036  -1.73763089]]
Data where name is not Will
 [[-0.537603    1.10484444  0.29149509 -0.70567684]
 [-0.02148982 -0.84863503 -0.06717231 -1.12243995]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [48]:
Random2D = np.random.uniform(1,15,(5,3))
Random2D

array([[ 1.17051579,  8.04634728,  7.33162777],
       [ 6.57303763,  2.51656327, 12.86835888],
       [ 7.08836855,  1.03873535, 13.17097949],
       [ 1.63905343, 13.21091086,  7.28247902],
       [ 7.84074375, 10.81193307,  9.60737145]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [49]:
Random3D = np.random.uniform(1,16,(2,2,4))
Random3D

array([[[ 1.09555845,  6.69487019,  3.81719663,  6.04008154],
        [ 3.1099584 , 14.22961579,  8.22824266,  9.61638783]],

       [[ 3.7828838 ,  1.79862475, 15.90277585,  8.94758032],
        [10.08011458,  9.3074373 ,  6.1856401 ,  4.10107403]]])

33. Swap axes of the array you created in Question 32

In [50]:
arr = np.swapaxes(Random3D, 1, 2)
arr

array([[[ 1.09555845,  3.1099584 ],
        [ 6.69487019, 14.22961579],
        [ 3.81719663,  8.22824266],
        [ 6.04008154,  9.61638783]],

       [[ 3.7828838 , 10.08011458],
        [ 1.79862475,  9.3074373 ],
        [15.90277585,  6.1856401 ],
        [ 8.94758032,  4.10107403]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [51]:

arr = np.random.randint(low = 4, high = 10, size = (5, 6))
print("Array: \n", arr)

sqrt_arr = np.sqrt(arr)
print("Square root result is: \n", sqrt_arr)

Array: 
 [[6 4 4 5 4 4]
 [4 9 9 5 7 7]
 [9 8 8 5 5 9]
 [5 5 4 5 5 4]
 [8 7 4 9 8 8]]
Square root result is: 
 [[2.44948974 2.         2.         2.23606798 2.         2.        ]
 [2.         3.         3.         2.23606798 2.64575131 2.64575131]
 [3.         2.82842712 2.82842712 2.23606798 2.23606798 3.        ]
 [2.23606798 2.23606798 2.         2.23606798 2.23606798 2.        ]
 [2.82842712 2.64575131 2.         3.         2.82842712 2.82842712]]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [52]:
arr1 = np.random.randint(0,12,(12))
arr2 = np.random.randint(0,12,(12))
max_arr = np.maximum(arr1, arr2)
print("array 1 is: ", arr1)
print("array 2 is: ", arr2)
print("max values: ", max_arr)

array 1 is:  [ 4  7  6  6  8  3  7  7 10 10  7  7]
array 2 is:  [ 5  0 11  3 11  0  1  9  3  6  6 10]
max values:  [ 5  7 11  6 11  3  7  9 10 10  7 10]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [53]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
unique_names = np.unique(names)
sorted_unique_names = np.sort(unique_names)

sorted_unique_names


array(['Bob', 'Joe', 'Will'], dtype='<U4')


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [54]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
arr = np.setdiff1d(a,b)
arr

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [55]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])

print("Actual Array: \n", sampleArray)

sampleArray[:,1] = newColumn

print("After Replacing comlumn: \n", sampleArray)

Actual Array: 
 [[34 43 73]
 [82 22 12]
 [53 94 66]]
After Replacing comlumn: 
 [[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [56]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
dot_product = np.dot(x,y)
print("The dot product is: \n", dot_product)

The dot product is: 
 [[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [57]:
mat = np.random.rand(20)
print("The matrix is: \n", mat)
print("The cumulative sum is: \n", mat.cumsum())

The matrix is: 
 [0.67209375 0.72233438 0.8017652  0.42755632 0.81709854 0.40446432
 0.8136596  0.22364707 0.44971177 0.42799506 0.78826694 0.60497514
 0.14934839 0.84997031 0.16390103 0.39088683 0.73986356 0.20572003
 0.95308526 0.30911264]
The cumulative sum is: 
 [ 0.67209375  1.39442812  2.19619332  2.62374964  3.44084818  3.8453125
  4.6589721   4.88261917  5.33233095  5.76032601  6.54859295  7.15356808
  7.30291648  8.15288679  8.31678782  8.70767465  9.44753821  9.65325824
 10.60634349 10.91545614]
