# **Assignment For Numpy**

**Name** : Abdullah Zahid 

**Roll No.**: PIAIC142504

**Batch**: 34

**Session**: 4

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [6]:
vector1 = np.arange(10, 50)

4. Find the shape of previous array in question 3

In [17]:
print("The shape of array is: ", vector1.shape)

The shape of array is:  (40,)


In [18]:
print("The shape of array is: ", np.shape(vector1))

The shape of array is:  (40,)


5. Print the type of the previous array in question 3

In [20]:
print("The type of vector:", type(vector1))

The type of vector: <class 'numpy.ndarray'>


In [21]:
print("The data type of array: ", vector1.dtype)

The data type of array:  int32


6. Print the numpy version and the configuration


In [24]:
print("The version of Numpy is: ", np.__version__)

The version of Numpy is:  1.18.1


Or

In [26]:
print("The version of Numpy is: ", np.version.version)

The version of Numpy is:  1.18.1


In [25]:
print("The Configuration of Numpy is: ", np.show_config())

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/ProgramData/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 

7. Print the dimension of the array in question 3


In [30]:
vector1.ndim

1

Or

In [31]:
np.ndim(vector1)

1

8. Create a boolean array with all the True values

In [36]:
BooleanVector = np.ones(10,dtype = bool)
BooleanVector

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [45]:
Vector_2D_Ones = np.ones((2,5))
Vector_2D_Ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [39]:
np.arange(8).reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [40]:
np.array([[1,2,3,4,5],[6,7,8,9,10]])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

10. Create a three dimensional array



In [41]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [43]:
np.arange(24).reshape(2,3,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [49]:
Vector2 = np.arange(5)
print("The array is: ", Vector2)
Reversed_Vector = Vector2[::-1]
print("The reversed vector is: ", Reversed_Vector)

The array is:  [0 1 2 3 4]
The reversed vector is:  [4 3 2 1 0]


12. Create a null vector of size 10 but the fifth value which is 1 

In [52]:
Vector3 = np.zeros(10)
Vector3[4] = 1
Vector3

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [54]:
identity_mat = np.identity(3)
identity_mat


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [65]:
arr = np.array([1, 2, 3, 4, 5])
print("The type of arr is: ", arr.dtype)
arr = arr.astype("float16")
print("new type of arr is:", arr.dtype)

The type of arr is:  int32
new type of arr is: float16


15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [69]:
arr1 = np.array([[1., 2., 3.],
                 [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],
                 [7., 2., 12.]])

pro_arr = arr1 * arr2

print("Multiplication of both vectors are: \n", pro_arr)

Multiplication of both vectors are: 
 [[ 0.  8.  3.]
 [28. 10. 72.]]


16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [70]:
arr1 = np.array([[1., 2., 3.],
                 [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],
                 [7., 2., 12.]])

In [72]:
arr_gt = arr1 > arr2
arr_gt

array([[ True, False,  True],
       [False,  True, False]])

In [74]:
arr_lt = arr1 < arr2
arr_lt

array([[False,  True, False],
       [ True, False,  True]])

In [76]:
arr_eq = arr1 == arr2
arr_eq

array([[False, False, False],
       [False, False, False]])

In [77]:
arr_neq = arr1 != arr2
arr_neq

array([[ True,  True,  True],
       [ True,  True,  True]])

17. Extract all odd numbers from arr with values(0-9)

In [85]:
arr4 = np.arange(10)
odds = arr4[arr4 % 2 == 1]
odds

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [88]:
arr4[arr4 % 2 == 1] =-1
arr4

array([-1, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [90]:
arr = np.arange(10)
indices = [5,6,7,8]

arr[indices] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [97]:
arr = np.ones((4, 5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [98]:
arr[1:-1,1:-1]=0
arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [100]:
arr2d = np.array([[1, 2, 3],
                  [4, 5, 6], 
                  [7, 8, 9]])

arr2d[1,1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [103]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0][0] = 64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [107]:
arr = np.arange(10).reshape(2,5)
sliced_arr = arr[0]
sliced_arr

array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [108]:
arr = np.arange(10).reshape(2,5)
sliced_arr = arr[1]
sliced_arr

array([5, 6, 7, 8, 9])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [120]:
arr = np.arange(10).reshape(2,5)
sliced_arr = arr[0:2,3]
sliced_arr

array([3, 8])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [128]:
arr = np.random.randint(1, 50, size = (10, 10))
arr

array([[23,  4, 33, 20, 23, 14, 18, 11,  1, 26],
       [35, 40, 43,  5, 43, 44, 14, 24,  5, 32],
       [ 9, 31,  7, 19, 23, 25,  4, 40, 32, 13],
       [42, 37, 43, 14, 24, 42, 32, 27,  8, 21],
       [31, 30, 17, 12, 21,  9, 43, 22,  4, 33],
       [46,  2, 27, 36, 48,  4, 28, 31, 45,  6],
       [46, 15, 17, 36,  5,  2, 12,  8, 45, 47],
       [24, 37, 25,  8, 15, 40, 37, 13, 25, 25],
       [ 1, 31, 12, 34, 23, 12, 15, 46, 17, 42],
       [47, 13,  1, 20, 23, 33,  3, 21,  3, 49]])

In [133]:
print("The Max Value in array is: ", arr.max())

The Max Value in array is:  49


or

In [134]:
print("The Max Value in array is: ", np.max(arr))

The Max Value in array is:  49


In [135]:
print("The Min Value in array is: ", arr.min())

The Min Value in array is:  1


In [136]:
print("The Min Value in array is: ", np.min(arr))

The Min Value in array is:  1


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [165]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])

comm_arr = np.intersect1d(a,b)
comm_arr

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [168]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
arr = np.in1d(a, comm_arr)
np.where(arr==True)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [185]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print("Data is :\n", data)

ext_data = data[names!="Will"]

print("Data where name is not Will\n", ext_data)

Data is :
 [[-0.43466218 -1.25871201 -1.77183136  2.04051945]
 [-0.06105136 -1.56595875  0.62765917 -0.39904437]
 [ 0.51996736  1.74368454 -0.64467244 -0.61464636]
 [-1.09461087 -0.24404327  0.46543093  2.3236319 ]
 [-0.13226421 -2.18531054  0.2343762  -0.69477013]
 [-0.16146566 -1.98719629 -0.06450488 -0.76966987]
 [ 1.75901292  0.24641337  1.03922841 -0.12231717]]
Data where name is not Will
 [[-0.43466218 -1.25871201 -1.77183136  2.04051945]
 [-0.06105136 -1.56595875  0.62765917 -0.39904437]
 [-1.09461087 -0.24404327  0.46543093  2.3236319 ]
 [-0.16146566 -1.98719629 -0.06450488 -0.76966987]
 [ 1.75901292  0.24641337  1.03922841 -0.12231717]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [189]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)

print("Data is :\n", data)

ext_data = data[np.logical_and(names != "Will", names != "Joe")]


print("Data where name is not Will\n", ext_data)

Data is :
 [[ 0.605329   -0.67964101 -1.69231695  0.52736657]
 [-0.4741228   1.40594217 -0.16629421 -1.05867687]
 [-0.00392181 -0.6054489  -0.56532836  2.25343543]
 [ 0.32865523  0.43728169 -0.33728029  0.12260333]
 [ 2.22816974  1.01839999  0.22210788  1.39467879]
 [-0.02953514 -0.15335261 -0.34239423  1.37323274]
 [-0.9152888  -0.16379459  0.4804335   0.55119094]]
Data where name is not Will
 [[ 0.605329   -0.67964101 -1.69231695  0.52736657]
 [ 0.32865523  0.43728169 -0.33728029  0.12260333]]


Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [191]:
Random2D = np.random.uniform(1,15,(5,3))
Random2D

array([[11.93044365,  3.25924418, 12.14566814],
       [ 4.91367065,  6.76327088,  2.20359995],
       [12.17893133,  5.28714719,  3.92161496],
       [ 6.14586961,  4.50866902, 10.62347355],
       [12.05584453,  6.61303235,  9.7395818 ]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [192]:
Random3D = np.random.uniform(1,16,(2,2,4))
Random3D

array([[[11.66284604,  9.07902772, 10.36942224, 12.96069177],
        [ 7.70295898,  2.68431847,  1.772586  ,  6.96629485]],

       [[ 1.93124163, 12.23825658,  7.86347894, 10.18254746],
        [ 2.94745191, 10.81265117, 13.99378186,  1.4385422 ]]])

33. Swap axes of the array you created in Question 32

In [195]:
arr = np.swapaxes(Random3D, 1, 2)
arr

array([[[11.66284604,  7.70295898],
        [ 9.07902772,  2.68431847],
        [10.36942224,  1.772586  ],
        [12.96069177,  6.96629485]],

       [[ 1.93124163,  2.94745191],
        [12.23825658, 10.81265117],
        [ 7.86347894, 13.99378186],
        [10.18254746,  1.4385422 ]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [204]:

arr = np.random.randint(low = 4, high = 10, size = (5, 6))
print("Array: \n", arr)

sqrt_arr = np.sqrt(arr)
print("Square root result is: \n", sqrt_arr)

Array: 
 [[7 5 9 6 4 7]
 [9 6 7 5 4 7]
 [5 5 7 9 6 9]
 [5 7 5 5 5 5]
 [7 7 6 6 6 5]]
Square root result is: 
 [[2.64575131 2.23606798 3.         2.44948974 2.         2.64575131]
 [3.         2.44948974 2.64575131 2.23606798 2.         2.64575131]
 [2.23606798 2.23606798 2.64575131 3.         2.44948974 3.        ]
 [2.23606798 2.64575131 2.23606798 2.23606798 2.23606798 2.23606798]
 [2.64575131 2.64575131 2.44948974 2.44948974 2.44948974 2.23606798]]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [211]:
arr1 = np.random.randint(0,12,(12))
arr2 = np.random.randint(0,12,(12))
max_arr = np.maximum(arr1, arr2)
print("array 1 is: ", arr1)
print("array 2 is: ", arr2)
print("max values: ", max_arr)

array 1 is:  [ 1  9  9  3  9 10  8  8 10  8  0  6]
array 2 is:  [ 9  4  5 11 10  5 11  9  5  7  0  7]
max values:  [ 9  9  9 11 10 10 11  9 10  8  0  7]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [215]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
unique_names = np.unique(names)
sorted_unique_names = np.sort(unique_names)

sorted_unique_names


array(['Bob', 'Joe', 'Will'], dtype='<U4')


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [220]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
arr = np.setdiff1d(a,b)
arr

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [230]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
newColumn = np.array([[10,10,10]])

print("Actual Array: \n", sampleArray)

sampleArray[:,1] = newColumn

print("After Replacing comlumn: \n", sampleArray)

Actual Array: 
 [[34 43 73]
 [82 22 12]
 [53 94 66]]
After Replacing comlumn: 
 [[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [234]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
dot_product = np.dot(x,y)
print("The dot product is: \n", dot_product)

The dot product is: 
 [[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [242]:
mat = np.random.rand(20)
print("The matrix is: \n", mat)
print("The cumulative sum is: \n", mat.cumsum())

The matrix is: 
 [0.8928291  0.92222531 0.79430837 0.7006324  0.67854978 0.59012899
 0.04765415 0.46545365 0.58140883 0.40697602 0.19007263 0.93125864
 0.93500598 0.33779238 0.79720039 0.39806347 0.06169913 0.74469353
 0.53318833 0.89715181]
The cumulative sum is: 
 [ 0.8928291   1.8150544   2.60936278  3.30999518  3.98854496  4.57867395
  4.6263281   5.09178175  5.67319059  6.08016661  6.27023924  7.20149788
  8.13650386  8.47429624  9.27149663  9.6695601   9.73125923 10.47595276
 11.00914108 11.90629289]
