# Numpy_Assignment_2::

In [2]:
import numpy as np

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [3]:
arr = np.arange(10)
print("The array:")
print(arr)
arr = arr.reshape(2,5)
print("Array after reshape: \n", arr)

The array:
[0 1 2 3 4 5 6 7 8 9]
Array after reshape: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]


## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [9]:
arr1 = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9]])
arr2 = np.array([[1, 1, 1, 1, 1], [1, 1, 1, 1, 1]])
arr3 = np.vstack((arr1, arr2))
arr3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [12]:
arr4 = np.arange(10).reshape(2,5)
arr5 = np.ones((2,5))
arr6 = np.hstack((arr4, arr5))
arr6

array([[0., 1., 2., 3., 4., 1., 1., 1., 1., 1.],
       [5., 6., 7., 8., 9., 1., 1., 1., 1., 1.]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [14]:
arr7 = np.arange(10).reshape(2,5)
arr8 = arr7.flatten()
arr8

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [15]:
arr7 = np.arange(15).reshape(1,3,5)
arr8 = arr7.flatten()
arr8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [17]:
arr9 = np.arange(15)
arr10 = arr9.reshape(5, 3)
arr10

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [19]:
arr11 = np.random.randint(1,10,(5,5))
np.square(arr11)

array([[16,  1, 36,  9, 25],
       [49, 16,  9,  1, 25],
       [49, 81, 25,  1,  4],
       [36, 36, 36,  1, 25],
       [ 9, 36, 49, 64, 81]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [27]:
arr12 = np.random.randint(1,10,(5,6))
print("Array is : \n", arr12)
mean_val = np.mean(arr12)
mean_val

Array is : 
 [[1 9 6 7 3 8]
 [8 4 4 6 5 8]
 [1 5 3 5 1 3]
 [4 9 5 5 4 8]
 [7 8 9 2 2 1]]


5.033333333333333

## Question:9

### Find the standard deviation of the previous array in Q8?

In [28]:
std_val = np.std(arr12)
std_val

2.5882211823738883

## Question:10

### Find the median of the previous array in Q8?

In [29]:
median_val = np.median(arr12)
median_val

5.0

## Question:11

### Find the transpose of the previous array in Q8?

In [30]:
arr12.T

array([[1, 8, 1, 4, 7],
       [9, 4, 5, 9, 8],
       [6, 4, 3, 5, 9],
       [7, 6, 5, 5, 2],
       [3, 5, 1, 4, 2],
       [8, 8, 3, 8, 1]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [33]:
arr13 = np.random.randint(1,10,(4,4))
print("Array is: \n",arr13)
dia_sum = arr13.trace()
dia_sum

Array is: 
 [[4 4 9 7]
 [4 8 6 8]
 [9 9 1 9]
 [1 7 8 5]]


18

## Question:13

### Find the determinant of the previous array in Q12?

In [35]:
det = np.linalg.det(arr13)
det

568.0000000000001

## Question:14

### Find the 5th and 95th percentile of an array?

In [36]:
percentile_5th_95th = np.percentile(arr13, [5, 95])
percentile_5th_95th

array([1., 9.])

## Question:15

### How to find if a given array has any null values?

using ``isnan()`` method

In [41]:
arr14 = np.array([1,2,4,np.nan,5])
arr14

array([ 1.,  2.,  4., nan,  5.])

In [44]:
np.isnan(arr14).any()

True